# Generated by Django 6.0.5 on 2026-05-16 06:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tbl_Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(default='', max_length=300)),
                ('option1', models.CharField(default='', max_length=30)),
                ('option2', models.CharField(default='', max_length=50)),
                ('option3', models.CharField(default='', max_length=30)),
                ('option4', models.CharField(default='', max_length=30)),
                ('question_type', models.CharField(default='Admin', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Tbl_User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30)),
                ('gender', models.CharField(default='', max_length=30)),
                ('phone', models.CharField(default='', max_length=50)),
                ('dob', models.CharField(default='', max_length=30)),
                ('address', models.CharField(default='', max_length=30)),
                ('email', models.CharField(default='', max_length=30)),
                ('pswd', models.CharField(default='', max_length=30)),
                ('status', models.CharField(default='', max_length=30)),
                ('user_type', models.CharField(default='', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Tbl_selfcorner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub', models.CharField(default='', max_length=30)),
                ('journal', models.CharField(default='', max_length=30)),
                ('date', models.CharField(default='', max_length=50)),
                ('tip', models.CharField(default='', max_length=50)),
                ('tip_date', models.CharField(default='', max_length=50)),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='metalhealthapp.tbl_user')),
            ],
        ),
        migrations.CreateModel(
            name='Tbl_result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(default='', max_length=300)),
                ('total', models.CharField(default='', max_length=300)),
                ('status', models.CharField(default='', max_length=300)),
                ('doctor', models.CharField(default='0', max_length=50)),
                ('report_status', models.CharField(default='', max_length=300)),
                ('description', models.CharField(default='', max_length=300)),
                ('user_ID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='metalhealthapp.tbl_user')),
            ],
        ),
        migrations.CreateModel(
            name='Tbl_Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.CharField(default='', max_length=30)),
                ('date', models.CharField(default='', max_length=30)),
                ('status', models.CharField(default='', max_length=50)),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='metalhealthapp.tbl_user')),
            ],
        ),
    ]
